name: seal-tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: MatteoH2O1999/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install dependencies (time-machine pinned to release date)
        run: |
          python -m pip install --index-url 'https://:2018-12-07T13:40:06.872228Z@time-machines-pypi.sealsecurity.io/' --upgrade pip setuptools wheel
          python -m pip install atomicwrites
          python -m pip install --index-url 'https://:2018-12-07T13:40:06.872228Z@time-machines-pypi.sealsecurity.io/' '.[test,crypto]'
      - name: Run tests
        run: python -m pytest tests/
